config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tasks do
    collection do
      post :confirm
    end
  end
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true
  validate :start_check
  def start_check
    errors.add(:time_limit, "は現在より未来の日時を選択してください") if time_limit < Time.now
    errors.add(:status, "を選択してください") if status == '選択してください'
  end
  enum status: { '選択してください':0, 未着手: 1, 着手中: 2, 完了: 3 }
  enum priority: { 高: 1, 中: 2, 低: 3 }
  scope :fuzzy_by_title, ->(params) { where('title LIKE ?', "%#{params}%") }
  scope :full_by_status, ->(params) { where(status: params) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  before_update :do_not_update_if_admin_will_be_zero
  before_destroy :do_not_destroy_last_admin
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  enum admin: { あり: true, なし: false }
  private
  def do_not_destroy_last_admin
    if User.where(admin: :true).count == 1 && self.admin == "あり"
      errors.add :base, '管理者は少なくとも1人は必要です'
      throw :abort
    end
  end
  def do_not_update_if_admin_will_be_zero
    user = User.where(admin: :true)
    if user.count == 1 && self.admin == "なし"
      errors.add :base, '管理者は少なくとも1人は必要です'
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.includes(:tasks)
    @users = @users.page(params[:page]).per(10)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to admin_users_path, notice: "新規作成しました！"
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "更新しました！"
    else
      render :edit
    end
  end
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "削除しました！"
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
  def access_limit_after_login
    redirect_to user_path(current_user.id) if current_user
  end
  def if_not_admin
    if current_user && current_user.admin == "なし"
      flash[:danger] = '管理者ではないのでアクセスできません'
      redirect_to tasks_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'ログインに成功しました！'
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = current_user.tasks.order(created_at: :DESC)
    @tasks = current_user.tasks.order(time_limit: :DESC) if params[:sort_expired]
    @tasks = current_user.tasks.order(:priority) if params[:sort_priority]
    if params[:task].present?
      if params[:task][:title].present? && params[:task][:status] != '選択してください'
        @tasks = current_user.tasks.fuzzy_by_title(params[:task][:title]).full_by_status(params[:task][:status])
      elsif params[:task][:title].present? && params[:task][:status] == '選択してください'
        @tasks = current_user.tasks.fuzzy_by_title(params[:task][:title])
      elsif params[:task][:label_id].present?
        # パターン1：
        # labelsテーブルと内部結合したtasksテーブルのcurrent_userのレコードを取得する
        # パラメータのidを持つlabelと結合しているレコードを取り出す
        @tasks = current_user.tasks.joins(:labels).where(labels: { id: params[:task][:label_id] })
        # パターン2：パラメータのidを持つlabelのレコードを取得し、それに紐づくtaskのレコードを取り出す
        # @tasks = Label.find(params[:task][:label_id]).tasks
        # パターン3：
        # パラメータのidを持つlabelのレコードを取得し、それに紐づくtaskのidを変数ids_taskに代入
        # current_userのtaskレコードの中で、idがids_taskのレコードを取り出す
        # ids_task = Label.find(params[:task][:label_id]).task_ids
        # @tasks = current_user.tasks.where(id: ids_task)
      elsif params[:task][:status] != '選択してください'
        @tasks = current_user.tasks.full_by_status(params[:task][:status])
      end
    end
    @tasks = @tasks.page(params[:page]).per(10)
  end
  def new
    @task = Task.new
  end
  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end
  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "新規作成しました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "更新しました！"
    else
      render :edit
    end
  end
  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "削除しました！"
  end
  private
  def task_params
    params.require(:task).permit(:title, :content, :time_limit, :status, :priority, { label_ids: [] })
  end
  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :access_limit_after_login, only: [:new]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
    redirect_to tasks_path unless @user.id == current_user.id
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
  def choose_new_or_edit_admin
    if action_name == 'new' || action_name == 'create'
      admin_users_path
    elsif action_name == 'edit' || action_name == 'update'
      admin_user_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: @user, local: true, url: choose_new_or_edit_admin ) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task-form form_group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :admin %>
    <%= form.select :admin, User.admins.keys, id: 'user_admin' %>
  </div>
  <div class="text-center">
    <%= form.submit "登録する", class: 'btn btn-primary' %>
  </div>
<% end %>
<br>
<%= link_to t('view.user_list'), admin_users_path %>

app/views/admin/users/edit.html.erb
<div class="flex-container">
  <div>
    <h2><%= t('view.edit') %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h2><%= t('view.administrator_user_list') %></h2>
  </div>
</div>
<div class="btn-new">
  <%= link_to t('view.new'), new_admin_user_path, class: 'btn btn-primary' %>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th><%= t('view.name') %></th>
      <th><%= t('view.email') %></th>
      <th><%= t('view.task_number') %></th>
      <th><%= t('view.admin') %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each.with_index(1) do |user, number| %>
      <tr id="user_row">
        <td><%= number %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= user.admin %></td>
        <td><%= link_to t('view.detail'), admin_user_path(user.id), class: 'btn btn-info btn-sm btn-info-customize' %></td>
        <td><%= link_to t('view.edit'), edit_admin_user_path(user.id), class: 'btn btn-success btn-sm btn-success-customize' %></td>
        <td><%= link_to link_to t('view.delete'), admin_user_path(user.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger btn-sm btn-danger-customize' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<div class="flex-container">
  <div>
    <h2><%= t('view.new') %></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/show.html.erb
<h2><%= "#{@user.name}さんの" %><%= t('view.task_list') %></h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th><%= t('view.name') %></th>
      <th><%= t('view.title') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.time_limit') %></th>
      <th><%= t('view.status') %></th>
      <th><%= t('view.priority') %></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each.with_index(1) do |task, number| %>
      <tr id="task_row">
        <td><%= number %></td>
        <td><%= task.user.name %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= l task.time_limit, format: :short %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <%= link_to t('view.profile'), user_path(current_user.id) %>
        <%= link_to t('view.log_out'), session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to t('view.sign_up'), new_user_path %>
        <%= link_to t('view.log_in'), new_session_path %>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task-form form_group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control' %>
  </div>
  <div class="task-form form_group">
    <%= form.label :time_limit, class: 'content-margin' %>
    <%= form.datetime_select :time_limit %>
  </div>
  <div class="task-form form_group">
    <%= form.label :status, class: 'content-margin' %>
    <%= form.select :status, Task.statuses.keys %>
  </div>
  <div class="task-form form_group">
    <%= form.label :priority, class: 'content-margin' %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>
  <div class="field">
    <%= form.label 'ラベル名', class: 'content-margin' %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  <div class="text-center">
    <%= form.submit "登録する", class: 'btn btn-primary' %>
  </div>
<% end %>
<br>
<%= link_to t('view.task_list'), tasks_path %>

app/views/tasks/confirm.html.erb
<div class="flex-container">
  <div>
    <h3><%= t('view.send_with_the_following_contents') %></h3>
    <%= form_with(model: @task, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :time_limit %>
      <%= form.hidden_field :status %>
      <%= form.hidden_field :priority %>
      <p><%= t('view.title') %>:<%= @task.title %></p>
      <p><%= t('view.content') %>:<%= @task.content %></p>
      <p><%= t('view.time_limit') %>:<%= @task.time_limit.strftime("%Y年%m月%d日%H時%M分") %></p>
      <p><%= t('view.status') %>:<%= @task.status %></p>
      <p><%= t('view.priority') %>:<%= @task.priority %></p>
      <div class="field">
        <%= form.label :label_name, class: 'content-margin' %>
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
      </div>
      <%= form.submit "登録する", class: 'btn btn-primary btn-new' %>
      <%= form.submit "戻る", name: 'back', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h2><%= t('view.task_list') %></h2>
    <%= form_with(model: @tasks, url: tasks_path, method: :get, local: true) do |form| %>
      <div class="navbar-form">
        <div class="form_group">
          <%= form.label :タスク名, class: 'content-margin' %>
          <%= form.text_field :title, placeholder: 'Search a keyword', id: 'task_title', class: 'form-control content-margin' %>
          <%= form.label :ステータス, class: 'content-margin' %>
          <%= form.select :status, Task.statuses.keys, id: 'task_status' %>
          <%= form.label :ラベル名, class: 'content-margin-label' %>
          <%= form.select :label_id, Label.pluck(:name, :id), { include_blank: true } %>
          <%= form.submit "検索する", class: 'btn btn-default navbar-btn btn-sm btn-search' %>
        </div>
      </div>
    <% end %>
    <div class="btn-new">
      <%= link_to t('view.new'), new_task_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th><%= t('view.name') %></th>
      <th><%= t('view.title') %></th>
      <th><%= t('view.content') %></th>
      <th><%= link_to t('view.time_limit'), tasks_path(sort_expired: "true"), title: '終了期限でソートする' %></th>
      <th><%= t('view.status') %></th>
      <th><%= link_to t('view.priority'), tasks_path(sort_priority: "true"), title: '優先順位でソートする' %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each.with_index(1) do |task, number| %>
      <tr id="task_row">
        <td><%= number %></td>
        <td><%= task.user.name %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= l task.time_limit, format: :short %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to t('view.detail'), task_path(task.id), class: 'btn btn-info btn-sm btn-info-customize' %></td>
        <td><%= link_to t('view.edit'), edit_task_path(task.id), class: 'btn btn-success btn-sm btn-success-customize' %></td>
        <td><%= link_to link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger btn-sm btn-danger-customize' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>

app/views/tasks/show.html.erb
<div class="flex-container">
  <div>
    <h2><%= t('view.detail') %></h2>
    <p><%= t('view.title') %>：<%= @task.title %></p>
    <p><%= t('view.content') %>：<%= @task.content %></p>
    <p><%= t('view.time_limit') %>：<%= @task.time_limit.strftime("%Y年%m月%d日%H時%M分") %></p>
    <p><%= t('view.status') %>：<%= @task.status %></p>
    <p><%= t('view.priority') %>：<%= @task.priority %></p>
    <p><%= t('view.label_name') %>：
      <% @task.labels.each do |label| %>
        <% if label.id <= 2 %>
          <span class="label label-info">
        <% elsif label.id <= 4 %>
          <span class="label label-success">
        <% elsif label.id <= 6 %>
          <span class="label label-danger">
        <% else %>
          <span class="label label-default">
        <% end %>
        <%= label.name %></span>
      <% end %>
    </p>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex-container">
  <div>
    <h1><%= t('view.sign_up') %></h1>
    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="task-form form_group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="task-form form_group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="task-form form_group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="task-form form_group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="text-center">
        <%= f.submit "Create my account" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>